apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: virtual-customer
spec:
  podSelector:
    matchLabels:
      app: virtual-customer
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: order-service
      ports:
        - port: 3000
          protocol: TCP
