apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-service
spec:
  podSelector:
    matchLabels:
      app: ai-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: product-service
      ports:
        - port: 5001
          protocol: TCP
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Azure OpenAI HTTPS
    - ports:
        - port: 443
          protocol: TCP
