apiVersion: v1
kind: ConfigMap
metadata:
  name: makeline-service-config
data:
  # CosmosDB SQL API
  ORDER_DB_API: "cosmosdbsql"
  ORDER_DB_NAME: "orderdb"
  ORDER_DB_CONTAINER_NAME: "orders"
  ORDER_DB_PARTITION_KEY: "storeId"
  ORDER_DB_PARTITION_VALUE: "pets"
  AZURE_COSMOS_RESOURCEENDPOINT: "REPLACE_WITH_COSMOS_ENDPOINT"
  USE_WORKLOAD_IDENTITY_AUTH: "true"
  # Azure Service Bus
  AZURE_SERVICEBUS_FULLYQUALIFIEDNAMESPACE: "REPLACE_WITH_SB_NAMESPACE.servicebus.windows.net"
  ORDER_QUEUE_NAME: "orders"
  APPLICATIONINSIGHTS_ROLE_NAME: "makeline-service"
  APPINSIGHTS_CONNECTIONSTRING: "REPLACE_WITH_APPINSIGHTS_CONN_STR"
