apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: makeline-service-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: makeline-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: COSMOS_ENDPOINT
      remoteRef:
        key: cosmos-endpoint
