apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-admin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin.REPLACE_DOMAIN
      secretName: store-admin-tls
  rules:
    - host: admin.REPLACE_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-admin
                port:
                  number: 80
