apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: store-admin
spec:
  podSelector:
    matchLabels:
      app: store-admin
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 8081
          protocol: TCP
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: product-service
      ports:
        - port: 3002
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: makeline-service
      ports:
        - port: 3001
          protocol: TCP
