apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  AI_SERVICE_URL: "http://ai-service:5001/"
  APPLICATIONINSIGHTS_ROLE_NAME: "product-service"
  APPINSIGHTS_CONNECTIONSTRING: "REPLACE_WITH_APPINSIGHTS_CONN_STR"
