apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - cluster-secret-store.yaml
  - order-service/
  - makeline-service/
  - product-service/
  - ai-service/
  - store-front/
  - store-admin/
  - virtual-customer/
  - virtual-worker/
